Added componets and Redux
WictorT/randomly-priced-games pull request #3
Opened 2019-02-11 15:11 UTC by hi-dima

2019-02-12 07:37 UTC, WictorT requested changes

2019-02-12 07:37 UTC, WictorT commented on node/src/store/actions/products.js
> +            const response = await axios.get('http://192.168.99.100/api/products')
extract address to an environment variable

2019-02-12 07:37 UTC, WictorT commented on node/src/store/actions/products.js
> +        } catch (e) {
remove try/catch

2019-02-12 07:37 UTC, WictorT commented on node/src/index.js
> +    typeof window === 'object' &&
adjust code syntax and enable only in case of prod environment

2019-02-12 07:37 UTC, WictorT commented on node/src/store/actions/actionsTypes.js
> +export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
Add new line at the end of the file. Do this everywhere where needed

2019-02-12 07:37 UTC, WictorT commented on node/src/store/actions/products.js
> +export function fetchTodosSuccess(products) {
fix namming

2019-02-12 13:02 UTC, hi-dima commented on node/src/store/actions/products.js
> +            const response = await axios.get('http://192.168.99.100/api/products')
Done

2019-02-12 13:03 UTC, hi-dima commented on node/src/store/actions/products.js
> +        } catch (e) {
Done

2019-02-12 13:03 UTC, hi-dima commented on node/src/store/actions/actionsTypes.js
> +export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
Done

2019-02-12 13:03 UTC, hi-dima commented on node/src/store/actions/products.js
> +export function fetchTodosSuccess(products) {
Done

2019-02-12 13:12 UTC, hi-dima commented on node/src/index.js
> +    typeof window === 'object' &&
Done

2019-02-20 08:08 UTC, WictorT requested changes

2019-02-20 08:08 UTC, WictorT commented on node/src/store/actions/products.js
> +        const host = process.env.REACT_APP_HOST
add env file/

2019-02-20 08:08 UTC, WictorT commented on node/src/store/actions/products.js
> +        console.log(process.env)
remove console logs

2019-02-20 08:08 UTC, WictorT commented on node/src/App.js
> +import Header from "./componets/Header/Header";
Find a solution not to use relative paths when importing components

2019-02-20 08:08 UTC, WictorT commented on node/src/store/actions/products.js
> +        const host = process.env.REACT_APP_HOST
and name it API_PUBLIC_URL

2019-02-20 08:08 UTC, WictorT commented on node/src/store/actions/products.js
> +        const response = await axios.get(`${host}api/products`)
put `/` before api/products

2019-02-20 08:21 UTC, hi-dima commented on node/src/App.js
> +import Header from "./componets/Header/Header";
We added a new issue

2019-02-20 08:27 UTC, merged